name: qiime_extract_viz
owner: iuc
description: Extract vizualization from QIIME artifacts
long_description: |
  TODO
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/qiimme_extract_viz
homepage_url: http://www.qiime.org
type: unrestricted
categories:
 - Metagenomics
